module: Cloud SDK iOS Fiori
author: S_A_P
author_url: https://www.sap.com
root_url: https://pages.github.com/MarcoEidinger/cloud-sdk-ios-fiori
github_url: https://github.com/MarcoEidinger/cloud-sdk-ios-fiori
github_file_prefix: https://github.com/MarcoEidinger/cloud-sdk-ios-fiori/tree/master
theme: fullwidth
clean: true
copyright: '© 2020 [SAP](https://www.sap.com) under Apache 2.0.'
