name: Jazzy

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/jazzy.yml'
      - '.jazzy.yaml'
      - '**/*.md'
      - '**/*.jpg'
      - 'Gemfile*'
      - 'Package*'
      - 'Sources/**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/jazzy.yml'
      - '.jazzy.yaml'
      - '**/*.md'
      - '**/*.jpg'
      - 'Gemfile*'
      - 'Package*'
      - 'Sources/**/*.swift'

jobs:
  Jazzy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          brew install sourcekitten
          gem install jazzy
      - run: swift package generate-xcodeproj
      - run: xcodebuild build -scheme FioriSwiftUI-Package -sdk iphonesimulator
      - name: Generate documentation json and run jazzy
        run: ./scripts/docu-gen.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: API Docs
          path: docs
      - run: git fetch origin gh-pages:gh-pages
      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REMOTE_BRANCH: "gh-pages"
          FOLDER: "current"
        run: |
          REMOTE_REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout ${REMOTE_BRANCH}
          rm -rf ${FOLDER}/
          mv docs/ ${FOLDER}/
          git add --all ${FOLDER}
          git commit -m "Documentation for https://github.com/${GITHUB_REPOSITORY}/tree/${GITHUB_SHA}" -m "Generated by docu-gen.sh"
          git push ${REMOTE_REPO} ${REMOTE_BRANCH}
